// this file was autogenerated by params.rb 

 #include <string.h> 
#include "param_common.h" 
#include "params.h" 

void fill_param_desc(ParamDesc* desc) {strcpy(desc[PARAM_ADC_DAC_0_0].label, "adc_dac_0_0");
desc[PARAM_ADC_DAC_0_0].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_0_0].min = 0;
desc[PARAM_ADC_DAC_0_0].max = 0x7fffffff;
desc[PARAM_ADC_DAC_0_0].radix = 16;


strcpy(desc[PARAM_ADC_DAC_0_1].label, "adc_dac_0_1");
desc[PARAM_ADC_DAC_0_1].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_0_1].min = 0;
desc[PARAM_ADC_DAC_0_1].max = 0x7fffffff;
desc[PARAM_ADC_DAC_0_1].radix = 16;


strcpy(desc[PARAM_ADC_DAC_0_2].label, "adc_dac_0_2");
desc[PARAM_ADC_DAC_0_2].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_0_2].min = 0;
desc[PARAM_ADC_DAC_0_2].max = 0x7fffffff;
desc[PARAM_ADC_DAC_0_2].radix = 16;


strcpy(desc[PARAM_ADC_DAC_0_3].label, "adc_dac_0_3");
desc[PARAM_ADC_DAC_0_3].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_0_3].min = 0;
desc[PARAM_ADC_DAC_0_3].max = 0x7fffffff;
desc[PARAM_ADC_DAC_0_3].radix = 16;


strcpy(desc[PARAM_ADC_DAC_1_0].label, "adc_dac_1_0");
desc[PARAM_ADC_DAC_1_0].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_1_0].min = 0;
desc[PARAM_ADC_DAC_1_0].max = 0x7fffffff;
desc[PARAM_ADC_DAC_1_0].radix = 16;


strcpy(desc[PARAM_ADC_DAC_1_1].label, "adc_dac_1_1");
desc[PARAM_ADC_DAC_1_1].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_1_1].min = 0;
desc[PARAM_ADC_DAC_1_1].max = 0x7fffffff;
desc[PARAM_ADC_DAC_1_1].radix = 16;


strcpy(desc[PARAM_ADC_DAC_1_2].label, "adc_dac_1_2");
desc[PARAM_ADC_DAC_1_2].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_1_2].min = 0;
desc[PARAM_ADC_DAC_1_2].max = 0x7fffffff;
desc[PARAM_ADC_DAC_1_2].radix = 16;


strcpy(desc[PARAM_ADC_DAC_1_3].label, "adc_dac_1_3");
desc[PARAM_ADC_DAC_1_3].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_1_3].min = 0;
desc[PARAM_ADC_DAC_1_3].max = 0x7fffffff;
desc[PARAM_ADC_DAC_1_3].radix = 16;


strcpy(desc[PARAM_ADC_DAC_2_0].label, "adc_dac_2_0");
desc[PARAM_ADC_DAC_2_0].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_2_0].min = 0;
desc[PARAM_ADC_DAC_2_0].max = 0x7fffffff;
desc[PARAM_ADC_DAC_2_0].radix = 16;


strcpy(desc[PARAM_ADC_DAC_2_1].label, "adc_dac_2_1");
desc[PARAM_ADC_DAC_2_1].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_2_1].min = 0;
desc[PARAM_ADC_DAC_2_1].max = 0x7fffffff;
desc[PARAM_ADC_DAC_2_1].radix = 16;


strcpy(desc[PARAM_ADC_DAC_2_2].label, "adc_dac_2_2");
desc[PARAM_ADC_DAC_2_2].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_2_2].min = 0;
desc[PARAM_ADC_DAC_2_2].max = 0x7fffffff;
desc[PARAM_ADC_DAC_2_2].radix = 16;


strcpy(desc[PARAM_ADC_DAC_2_3].label, "adc_dac_2_3");
desc[PARAM_ADC_DAC_2_3].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_2_3].min = 0;
desc[PARAM_ADC_DAC_2_3].max = 0x7fffffff;
desc[PARAM_ADC_DAC_2_3].radix = 16;


strcpy(desc[PARAM_ADC_DAC_3_0].label, "adc_dac_3_0");
desc[PARAM_ADC_DAC_3_0].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_3_0].min = 0;
desc[PARAM_ADC_DAC_3_0].max = 0x7fffffff;
desc[PARAM_ADC_DAC_3_0].radix = 16;


strcpy(desc[PARAM_ADC_DAC_3_1].label, "adc_dac_3_1");
desc[PARAM_ADC_DAC_3_1].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_3_1].min = 0;
desc[PARAM_ADC_DAC_3_1].max = 0x7fffffff;
desc[PARAM_ADC_DAC_3_1].radix = 16;


strcpy(desc[PARAM_ADC_DAC_3_2].label, "adc_dac_3_2");
desc[PARAM_ADC_DAC_3_2].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_3_2].min = 0;
desc[PARAM_ADC_DAC_3_2].max = 0x7fffffff;
desc[PARAM_ADC_DAC_3_2].radix = 16;


strcpy(desc[PARAM_ADC_DAC_3_3].label, "adc_dac_3_3");
desc[PARAM_ADC_DAC_3_3].type = eParamTypeAmp;
desc[PARAM_ADC_DAC_3_3].min = 0;
desc[PARAM_ADC_DAC_3_3].max = 0x7fffffff;
desc[PARAM_ADC_DAC_3_3].radix = 16;


strcpy(desc[PARAM_OSC_DAC_0_0].label, "osc_dac_0_0");
desc[PARAM_OSC_DAC_0_0].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_0_0].min = 0;
desc[PARAM_OSC_DAC_0_0].max = 0x7fffffff;
desc[PARAM_OSC_DAC_0_0].radix = 16;


strcpy(desc[PARAM_OSC_DAC_0_1].label, "osc_dac_0_1");
desc[PARAM_OSC_DAC_0_1].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_0_1].min = 0;
desc[PARAM_OSC_DAC_0_1].max = 0x7fffffff;
desc[PARAM_OSC_DAC_0_1].radix = 16;


strcpy(desc[PARAM_OSC_DAC_0_2].label, "osc_dac_0_2");
desc[PARAM_OSC_DAC_0_2].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_0_2].min = 0;
desc[PARAM_OSC_DAC_0_2].max = 0x7fffffff;
desc[PARAM_OSC_DAC_0_2].radix = 16;


strcpy(desc[PARAM_OSC_DAC_0_3].label, "osc_dac_0_3");
desc[PARAM_OSC_DAC_0_3].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_0_3].min = 0;
desc[PARAM_OSC_DAC_0_3].max = 0x7fffffff;
desc[PARAM_OSC_DAC_0_3].radix = 16;


strcpy(desc[PARAM_OSC_DAC_1_0].label, "osc_dac_1_0");
desc[PARAM_OSC_DAC_1_0].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_1_0].min = 0;
desc[PARAM_OSC_DAC_1_0].max = 0x7fffffff;
desc[PARAM_OSC_DAC_1_0].radix = 16;


strcpy(desc[PARAM_OSC_DAC_1_1].label, "osc_dac_1_1");
desc[PARAM_OSC_DAC_1_1].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_1_1].min = 0;
desc[PARAM_OSC_DAC_1_1].max = 0x7fffffff;
desc[PARAM_OSC_DAC_1_1].radix = 16;


strcpy(desc[PARAM_OSC_DAC_1_2].label, "osc_dac_1_2");
desc[PARAM_OSC_DAC_1_2].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_1_2].min = 0;
desc[PARAM_OSC_DAC_1_2].max = 0x7fffffff;
desc[PARAM_OSC_DAC_1_2].radix = 16;


strcpy(desc[PARAM_OSC_DAC_1_3].label, "osc_dac_1_3");
desc[PARAM_OSC_DAC_1_3].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_1_3].min = 0;
desc[PARAM_OSC_DAC_1_3].max = 0x7fffffff;
desc[PARAM_OSC_DAC_1_3].radix = 16;


strcpy(desc[PARAM_OSC_DAC_2_0].label, "osc_dac_2_0");
desc[PARAM_OSC_DAC_2_0].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_2_0].min = 0;
desc[PARAM_OSC_DAC_2_0].max = 0x7fffffff;
desc[PARAM_OSC_DAC_2_0].radix = 16;


strcpy(desc[PARAM_OSC_DAC_2_1].label, "osc_dac_2_1");
desc[PARAM_OSC_DAC_2_1].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_2_1].min = 0;
desc[PARAM_OSC_DAC_2_1].max = 0x7fffffff;
desc[PARAM_OSC_DAC_2_1].radix = 16;


strcpy(desc[PARAM_OSC_DAC_2_2].label, "osc_dac_2_2");
desc[PARAM_OSC_DAC_2_2].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_2_2].min = 0;
desc[PARAM_OSC_DAC_2_2].max = 0x7fffffff;
desc[PARAM_OSC_DAC_2_2].radix = 16;


strcpy(desc[PARAM_OSC_DAC_2_3].label, "osc_dac_2_3");
desc[PARAM_OSC_DAC_2_3].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_2_3].min = 0;
desc[PARAM_OSC_DAC_2_3].max = 0x7fffffff;
desc[PARAM_OSC_DAC_2_3].radix = 16;


strcpy(desc[PARAM_OSC_DAC_3_0].label, "osc_dac_3_0");
desc[PARAM_OSC_DAC_3_0].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_3_0].min = 0;
desc[PARAM_OSC_DAC_3_0].max = 0x7fffffff;
desc[PARAM_OSC_DAC_3_0].radix = 16;


strcpy(desc[PARAM_OSC_DAC_3_1].label, "osc_dac_3_1");
desc[PARAM_OSC_DAC_3_1].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_3_1].min = 0;
desc[PARAM_OSC_DAC_3_1].max = 0x7fffffff;
desc[PARAM_OSC_DAC_3_1].radix = 16;


strcpy(desc[PARAM_OSC_DAC_3_2].label, "osc_dac_3_2");
desc[PARAM_OSC_DAC_3_2].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_3_2].min = 0;
desc[PARAM_OSC_DAC_3_2].max = 0x7fffffff;
desc[PARAM_OSC_DAC_3_2].radix = 16;


strcpy(desc[PARAM_OSC_DAC_3_3].label, "osc_dac_3_3");
desc[PARAM_OSC_DAC_3_3].type = eParamTypeAmp;
desc[PARAM_OSC_DAC_3_3].min = 0;
desc[PARAM_OSC_DAC_3_3].max = 0x7fffffff;
desc[PARAM_OSC_DAC_3_3].radix = 16;


strcpy(desc[PARAM_OSC_OSC_0_0].label, "osc_osc_0_0");
desc[PARAM_OSC_OSC_0_0].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_0_0].min = 0;
desc[PARAM_OSC_OSC_0_0].max = 0x7fffffff;
desc[PARAM_OSC_OSC_0_0].radix = 16;


strcpy(desc[PARAM_OSC_OSC_0_1].label, "osc_osc_0_1");
desc[PARAM_OSC_OSC_0_1].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_0_1].min = 0;
desc[PARAM_OSC_OSC_0_1].max = 0x7fffffff;
desc[PARAM_OSC_OSC_0_1].radix = 16;


strcpy(desc[PARAM_OSC_OSC_0_2].label, "osc_osc_0_2");
desc[PARAM_OSC_OSC_0_2].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_0_2].min = 0;
desc[PARAM_OSC_OSC_0_2].max = 0x7fffffff;
desc[PARAM_OSC_OSC_0_2].radix = 16;


strcpy(desc[PARAM_OSC_OSC_0_3].label, "osc_osc_0_3");
desc[PARAM_OSC_OSC_0_3].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_0_3].min = 0;
desc[PARAM_OSC_OSC_0_3].max = 0x7fffffff;
desc[PARAM_OSC_OSC_0_3].radix = 16;


strcpy(desc[PARAM_OSC_OSC_1_0].label, "osc_osc_1_0");
desc[PARAM_OSC_OSC_1_0].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_1_0].min = 0;
desc[PARAM_OSC_OSC_1_0].max = 0x7fffffff;
desc[PARAM_OSC_OSC_1_0].radix = 16;


strcpy(desc[PARAM_OSC_OSC_1_1].label, "osc_osc_1_1");
desc[PARAM_OSC_OSC_1_1].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_1_1].min = 0;
desc[PARAM_OSC_OSC_1_1].max = 0x7fffffff;
desc[PARAM_OSC_OSC_1_1].radix = 16;


strcpy(desc[PARAM_OSC_OSC_1_2].label, "osc_osc_1_2");
desc[PARAM_OSC_OSC_1_2].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_1_2].min = 0;
desc[PARAM_OSC_OSC_1_2].max = 0x7fffffff;
desc[PARAM_OSC_OSC_1_2].radix = 16;


strcpy(desc[PARAM_OSC_OSC_1_3].label, "osc_osc_1_3");
desc[PARAM_OSC_OSC_1_3].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_1_3].min = 0;
desc[PARAM_OSC_OSC_1_3].max = 0x7fffffff;
desc[PARAM_OSC_OSC_1_3].radix = 16;


strcpy(desc[PARAM_OSC_OSC_2_0].label, "osc_osc_2_0");
desc[PARAM_OSC_OSC_2_0].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_2_0].min = 0;
desc[PARAM_OSC_OSC_2_0].max = 0x7fffffff;
desc[PARAM_OSC_OSC_2_0].radix = 16;


strcpy(desc[PARAM_OSC_OSC_2_1].label, "osc_osc_2_1");
desc[PARAM_OSC_OSC_2_1].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_2_1].min = 0;
desc[PARAM_OSC_OSC_2_1].max = 0x7fffffff;
desc[PARAM_OSC_OSC_2_1].radix = 16;


strcpy(desc[PARAM_OSC_OSC_2_2].label, "osc_osc_2_2");
desc[PARAM_OSC_OSC_2_2].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_2_2].min = 0;
desc[PARAM_OSC_OSC_2_2].max = 0x7fffffff;
desc[PARAM_OSC_OSC_2_2].radix = 16;


strcpy(desc[PARAM_OSC_OSC_2_3].label, "osc_osc_2_3");
desc[PARAM_OSC_OSC_2_3].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_2_3].min = 0;
desc[PARAM_OSC_OSC_2_3].max = 0x7fffffff;
desc[PARAM_OSC_OSC_2_3].radix = 16;


strcpy(desc[PARAM_OSC_OSC_3_0].label, "osc_osc_3_0");
desc[PARAM_OSC_OSC_3_0].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_3_0].min = 0;
desc[PARAM_OSC_OSC_3_0].max = 0x7fffffff;
desc[PARAM_OSC_OSC_3_0].radix = 16;


strcpy(desc[PARAM_OSC_OSC_3_1].label, "osc_osc_3_1");
desc[PARAM_OSC_OSC_3_1].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_3_1].min = 0;
desc[PARAM_OSC_OSC_3_1].max = 0x7fffffff;
desc[PARAM_OSC_OSC_3_1].radix = 16;


strcpy(desc[PARAM_OSC_OSC_3_2].label, "osc_osc_3_2");
desc[PARAM_OSC_OSC_3_2].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_3_2].min = 0;
desc[PARAM_OSC_OSC_3_2].max = 0x7fffffff;
desc[PARAM_OSC_OSC_3_2].radix = 16;


strcpy(desc[PARAM_OSC_OSC_3_3].label, "osc_osc_3_3");
desc[PARAM_OSC_OSC_3_3].type = eParamTypeAmp;
desc[PARAM_OSC_OSC_3_3].min = 0;
desc[PARAM_OSC_OSC_3_3].max = 0x7fffffff;
desc[PARAM_OSC_OSC_3_3].radix = 16;


strcpy(desc[PARAM_OSC_ADC_0_0].label, "osc_adc_0_0");
desc[PARAM_OSC_ADC_0_0].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_0_0].min = 0;
desc[PARAM_OSC_ADC_0_0].max = 0x7fffffff;
desc[PARAM_OSC_ADC_0_0].radix = 16;


strcpy(desc[PARAM_OSC_ADC_0_1].label, "osc_adc_0_1");
desc[PARAM_OSC_ADC_0_1].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_0_1].min = 0;
desc[PARAM_OSC_ADC_0_1].max = 0x7fffffff;
desc[PARAM_OSC_ADC_0_1].radix = 16;


strcpy(desc[PARAM_OSC_ADC_0_2].label, "osc_adc_0_2");
desc[PARAM_OSC_ADC_0_2].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_0_2].min = 0;
desc[PARAM_OSC_ADC_0_2].max = 0x7fffffff;
desc[PARAM_OSC_ADC_0_2].radix = 16;


strcpy(desc[PARAM_OSC_ADC_0_3].label, "osc_adc_0_3");
desc[PARAM_OSC_ADC_0_3].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_0_3].min = 0;
desc[PARAM_OSC_ADC_0_3].max = 0x7fffffff;
desc[PARAM_OSC_ADC_0_3].radix = 16;


strcpy(desc[PARAM_OSC_ADC_1_0].label, "osc_adc_1_0");
desc[PARAM_OSC_ADC_1_0].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_1_0].min = 0;
desc[PARAM_OSC_ADC_1_0].max = 0x7fffffff;
desc[PARAM_OSC_ADC_1_0].radix = 16;


strcpy(desc[PARAM_OSC_ADC_1_1].label, "osc_adc_1_1");
desc[PARAM_OSC_ADC_1_1].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_1_1].min = 0;
desc[PARAM_OSC_ADC_1_1].max = 0x7fffffff;
desc[PARAM_OSC_ADC_1_1].radix = 16;


strcpy(desc[PARAM_OSC_ADC_1_2].label, "osc_adc_1_2");
desc[PARAM_OSC_ADC_1_2].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_1_2].min = 0;
desc[PARAM_OSC_ADC_1_2].max = 0x7fffffff;
desc[PARAM_OSC_ADC_1_2].radix = 16;


strcpy(desc[PARAM_OSC_ADC_1_3].label, "osc_adc_1_3");
desc[PARAM_OSC_ADC_1_3].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_1_3].min = 0;
desc[PARAM_OSC_ADC_1_3].max = 0x7fffffff;
desc[PARAM_OSC_ADC_1_3].radix = 16;


strcpy(desc[PARAM_OSC_ADC_2_0].label, "osc_adc_2_0");
desc[PARAM_OSC_ADC_2_0].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_2_0].min = 0;
desc[PARAM_OSC_ADC_2_0].max = 0x7fffffff;
desc[PARAM_OSC_ADC_2_0].radix = 16;


strcpy(desc[PARAM_OSC_ADC_2_1].label, "osc_adc_2_1");
desc[PARAM_OSC_ADC_2_1].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_2_1].min = 0;
desc[PARAM_OSC_ADC_2_1].max = 0x7fffffff;
desc[PARAM_OSC_ADC_2_1].radix = 16;


strcpy(desc[PARAM_OSC_ADC_2_2].label, "osc_adc_2_2");
desc[PARAM_OSC_ADC_2_2].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_2_2].min = 0;
desc[PARAM_OSC_ADC_2_2].max = 0x7fffffff;
desc[PARAM_OSC_ADC_2_2].radix = 16;


strcpy(desc[PARAM_OSC_ADC_2_3].label, "osc_adc_2_3");
desc[PARAM_OSC_ADC_2_3].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_2_3].min = 0;
desc[PARAM_OSC_ADC_2_3].max = 0x7fffffff;
desc[PARAM_OSC_ADC_2_3].radix = 16;


strcpy(desc[PARAM_OSC_ADC_3_0].label, "osc_adc_3_0");
desc[PARAM_OSC_ADC_3_0].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_3_0].min = 0;
desc[PARAM_OSC_ADC_3_0].max = 0x7fffffff;
desc[PARAM_OSC_ADC_3_0].radix = 16;


strcpy(desc[PARAM_OSC_ADC_3_1].label, "osc_adc_3_1");
desc[PARAM_OSC_ADC_3_1].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_3_1].min = 0;
desc[PARAM_OSC_ADC_3_1].max = 0x7fffffff;
desc[PARAM_OSC_ADC_3_1].radix = 16;


strcpy(desc[PARAM_OSC_ADC_3_2].label, "osc_adc_3_2");
desc[PARAM_OSC_ADC_3_2].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_3_2].min = 0;
desc[PARAM_OSC_ADC_3_2].max = 0x7fffffff;
desc[PARAM_OSC_ADC_3_2].radix = 16;


strcpy(desc[PARAM_OSC_ADC_3_3].label, "osc_adc_3_3");
desc[PARAM_OSC_ADC_3_3].type = eParamTypeAmp;
desc[PARAM_OSC_ADC_3_3].min = 0;
desc[PARAM_OSC_ADC_3_3].max = 0x7fffffff;
desc[PARAM_OSC_ADC_3_3].radix = 16;


strcpy(desc[PARAM_FREQ_FINE_0].label, "freq_fine_0");
desc[PARAM_FREQ_FINE_0].type = eParamTypeFix;
desc[PARAM_FREQ_FINE_0].min = 0;
desc[PARAM_FREQ_FINE_0].max = 0x7fffffff;
desc[PARAM_FREQ_FINE_0].radix = 16;


strcpy(desc[PARAM_FREQ_FINE_1].label, "freq_fine_1");
desc[PARAM_FREQ_FINE_1].type = eParamTypeFix;
desc[PARAM_FREQ_FINE_1].min = 0;
desc[PARAM_FREQ_FINE_1].max = 0x7fffffff;
desc[PARAM_FREQ_FINE_1].radix = 16;


strcpy(desc[PARAM_FREQ_FINE_2].label, "freq_fine_2");
desc[PARAM_FREQ_FINE_2].type = eParamTypeFix;
desc[PARAM_FREQ_FINE_2].min = 0;
desc[PARAM_FREQ_FINE_2].max = 0x7fffffff;
desc[PARAM_FREQ_FINE_2].radix = 16;


strcpy(desc[PARAM_FREQ_FINE_3].label, "freq_fine_3");
desc[PARAM_FREQ_FINE_3].type = eParamTypeFix;
desc[PARAM_FREQ_FINE_3].min = 0;
desc[PARAM_FREQ_FINE_3].max = 0x7fffffff;
desc[PARAM_FREQ_FINE_3].radix = 16;


strcpy(desc[PARAM_PHASE_0].label, "phase_0");
desc[PARAM_PHASE_0].type = eParamTypeFix;
desc[PARAM_PHASE_0].min = 0;
desc[PARAM_PHASE_0].max = 0x7fffffff;
desc[PARAM_PHASE_0].radix = 16;


strcpy(desc[PARAM_PHASE_1].label, "phase_1");
desc[PARAM_PHASE_1].type = eParamTypeFix;
desc[PARAM_PHASE_1].min = 0;
desc[PARAM_PHASE_1].max = 0x7fffffff;
desc[PARAM_PHASE_1].radix = 16;


strcpy(desc[PARAM_PHASE_2].label, "phase_2");
desc[PARAM_PHASE_2].type = eParamTypeFix;
desc[PARAM_PHASE_2].min = 0;
desc[PARAM_PHASE_2].max = 0x7fffffff;
desc[PARAM_PHASE_2].radix = 16;


strcpy(desc[PARAM_PHASE_3].label, "phase_3");
desc[PARAM_PHASE_3].type = eParamTypeFix;
desc[PARAM_PHASE_3].min = 0;
desc[PARAM_PHASE_3].max = 0x7fffffff;
desc[PARAM_PHASE_3].radix = 16;


strcpy(desc[PARAM_SHAPE_0].label, "shape_0");
desc[PARAM_SHAPE_0].type = eParamTypeFix;
desc[PARAM_SHAPE_0].min = 0;
desc[PARAM_SHAPE_0].max = 0x30000;
desc[PARAM_SHAPE_0].radix = 3;


strcpy(desc[PARAM_SHAPE_1].label, "shape_1");
desc[PARAM_SHAPE_1].type = eParamTypeFix;
desc[PARAM_SHAPE_1].min = 0;
desc[PARAM_SHAPE_1].max = 0x30000;
desc[PARAM_SHAPE_1].radix = 3;


strcpy(desc[PARAM_SHAPE_2].label, "shape_2");
desc[PARAM_SHAPE_2].type = eParamTypeFix;
desc[PARAM_SHAPE_2].min = 0;
desc[PARAM_SHAPE_2].max = 0x30000;
desc[PARAM_SHAPE_2].radix = 3;


strcpy(desc[PARAM_SHAPE_3].label, "shape_3");
desc[PARAM_SHAPE_3].type = eParamTypeFix;
desc[PARAM_SHAPE_3].min = 0;
desc[PARAM_SHAPE_3].max = 0x30000;
desc[PARAM_SHAPE_3].radix = 3;


strcpy(desc[PARAM_FREQ_COARSE_0].label, "freq_coarse_0");
desc[PARAM_FREQ_COARSE_0].type = eParamTypeFix;
desc[PARAM_FREQ_COARSE_0].min = 0;
desc[PARAM_FREQ_COARSE_0].max = 0x7fffffff;
desc[PARAM_FREQ_COARSE_0].radix = 16;


strcpy(desc[PARAM_FREQ_COARSE_1].label, "freq_coarse_1");
desc[PARAM_FREQ_COARSE_1].type = eParamTypeFix;
desc[PARAM_FREQ_COARSE_1].min = 0;
desc[PARAM_FREQ_COARSE_1].max = 0x7fffffff;
desc[PARAM_FREQ_COARSE_1].radix = 16;


strcpy(desc[PARAM_FREQ_COARSE_2].label, "freq_coarse_2");
desc[PARAM_FREQ_COARSE_2].type = eParamTypeFix;
desc[PARAM_FREQ_COARSE_2].min = 0;
desc[PARAM_FREQ_COARSE_2].max = 0x7fffffff;
desc[PARAM_FREQ_COARSE_2].radix = 16;


strcpy(desc[PARAM_FREQ_COARSE_3].label, "freq_coarse_3");
desc[PARAM_FREQ_COARSE_3].type = eParamTypeFix;
desc[PARAM_FREQ_COARSE_3].min = 0;
desc[PARAM_FREQ_COARSE_3].max = 0x7fffffff;
desc[PARAM_FREQ_COARSE_3].radix = 16;


  }