// this file was autogenerated by params.rb 

 void module_set_param(u32 idx, ParamValue val) { 
  switch(idx) { 
  case PARAM_ADC_DAC_0_0 : 
    mix_set_adc_dac(0, 0, val );
  break;

  case PARAM_ADC_DAC_0_1 : 
    mix_set_adc_dac(0, 1, val );
  break;

  case PARAM_ADC_DAC_0_2 : 
    mix_set_adc_dac(0, 2, val );
  break;

  case PARAM_ADC_DAC_0_3 : 
    mix_set_adc_dac(0, 3, val );
  break;

  case PARAM_ADC_DAC_1_0 : 
    mix_set_adc_dac(1, 0, val );
  break;

  case PARAM_ADC_DAC_1_1 : 
    mix_set_adc_dac(1, 1, val );
  break;

  case PARAM_ADC_DAC_1_2 : 
    mix_set_adc_dac(1, 2, val );
  break;

  case PARAM_ADC_DAC_1_3 : 
    mix_set_adc_dac(1, 3, val );
  break;

  case PARAM_ADC_DAC_2_0 : 
    mix_set_adc_dac(2, 0, val );
  break;

  case PARAM_ADC_DAC_2_1 : 
    mix_set_adc_dac(2, 1, val );
  break;

  case PARAM_ADC_DAC_2_2 : 
    mix_set_adc_dac(2, 2, val );
  break;

  case PARAM_ADC_DAC_2_3 : 
    mix_set_adc_dac(2, 3, val );
  break;

  case PARAM_ADC_DAC_3_0 : 
    mix_set_adc_dac(3, 0, val );
  break;

  case PARAM_ADC_DAC_3_1 : 
    mix_set_adc_dac(3, 1, val );
  break;

  case PARAM_ADC_DAC_3_2 : 
    mix_set_adc_dac(3, 2, val );
  break;

  case PARAM_ADC_DAC_3_3 : 
    mix_set_adc_dac(3, 3, val );
  break;

  case PARAM_OSC_DAC_0_0 : 
    mix_set_osc_dac(0, 0, val );
  break;

  case PARAM_OSC_DAC_0_1 : 
    mix_set_osc_dac(0, 1, val );
  break;

  case PARAM_OSC_DAC_0_2 : 
    mix_set_osc_dac(0, 2, val );
  break;

  case PARAM_OSC_DAC_0_3 : 
    mix_set_osc_dac(0, 3, val );
  break;

  case PARAM_OSC_DAC_1_0 : 
    mix_set_osc_dac(1, 0, val );
  break;

  case PARAM_OSC_DAC_1_1 : 
    mix_set_osc_dac(1, 1, val );
  break;

  case PARAM_OSC_DAC_1_2 : 
    mix_set_osc_dac(1, 2, val );
  break;

  case PARAM_OSC_DAC_1_3 : 
    mix_set_osc_dac(1, 3, val );
  break;

  case PARAM_OSC_DAC_2_0 : 
    mix_set_osc_dac(2, 0, val );
  break;

  case PARAM_OSC_DAC_2_1 : 
    mix_set_osc_dac(2, 1, val );
  break;

  case PARAM_OSC_DAC_2_2 : 
    mix_set_osc_dac(2, 2, val );
  break;

  case PARAM_OSC_DAC_2_3 : 
    mix_set_osc_dac(2, 3, val );
  break;

  case PARAM_OSC_DAC_3_0 : 
    mix_set_osc_dac(3, 0, val );
  break;

  case PARAM_OSC_DAC_3_1 : 
    mix_set_osc_dac(3, 1, val );
  break;

  case PARAM_OSC_DAC_3_2 : 
    mix_set_osc_dac(3, 2, val );
  break;

  case PARAM_OSC_DAC_3_3 : 
    mix_set_osc_dac(3, 3, val );
  break;

  case PARAM_OSC_ADC_0_0 : 
  break;

  case PARAM_OSC_ADC_0_1 : 
  break;

  case PARAM_OSC_ADC_0_2 : 
  break;

  case PARAM_OSC_ADC_0_3 : 
  break;

  case PARAM_OSC_ADC_1_0 : 
  break;

  case PARAM_OSC_ADC_1_1 : 
  break;

  case PARAM_OSC_ADC_1_2 : 
  break;

  case PARAM_OSC_ADC_1_3 : 
  break;

  case PARAM_OSC_ADC_2_0 : 
  break;

  case PARAM_OSC_ADC_2_1 : 
  break;

  case PARAM_OSC_ADC_2_2 : 
  break;

  case PARAM_OSC_ADC_2_3 : 
  break;

  case PARAM_OSC_ADC_3_0 : 
  break;

  case PARAM_OSC_ADC_3_1 : 
  break;

  case PARAM_OSC_ADC_3_2 : 
  break;

  case PARAM_OSC_ADC_3_3 : 
  break;

  case PARAM_OSC_OSC_0_0 : 
  break;

  case PARAM_OSC_OSC_0_1 : 
  break;

  case PARAM_OSC_OSC_0_2 : 
  break;

  case PARAM_OSC_OSC_0_3 : 
  break;

  case PARAM_OSC_OSC_1_0 : 
  break;

  case PARAM_OSC_OSC_1_1 : 
  break;

  case PARAM_OSC_OSC_1_2 : 
  break;

  case PARAM_OSC_OSC_1_3 : 
  break;

  case PARAM_OSC_OSC_2_0 : 
  break;

  case PARAM_OSC_OSC_2_1 : 
  break;

  case PARAM_OSC_OSC_2_2 : 
  break;

  case PARAM_OSC_OSC_2_3 : 
  break;

  case PARAM_OSC_OSC_3_0 : 
  break;

  case PARAM_OSC_OSC_3_1 : 
  break;

  case PARAM_OSC_OSC_3_2 : 
  break;

  case PARAM_OSC_OSC_3_3 : 
  break;

  case PARAM_FREQ_FINE_0 : 
    osc_set_phi_lower(0, val);
  break;

  case PARAM_FREQ_FINE_1 : 
    osc_set_phi_lower(1, val);
  break;

  case PARAM_FREQ_FINE_2 : 
    osc_set_phi_lower(2, val);
  break;

  case PARAM_FREQ_FINE_3 : 
    osc_set_phi_lower(3, val);
  break;

  case PARAM_PHASE_0 : 
    osc_set_phase(0, val);
  break;

  case PARAM_PHASE_1 : 
    osc_set_phase(1, val);
  break;

  case PARAM_PHASE_2 : 
    osc_set_phase(2, val);
  break;

  case PARAM_PHASE_3 : 
    osc_set_phase(3, val);
  break;

  case PARAM_PHASE_INC_0 : 
    osc_set_phase(0, val);
  break;

  case PARAM_PHASE_INC_1 : 
    osc_set_phase(1, val);
  break;

  case PARAM_PHASE_INC_2 : 
    osc_set_phase(2, val);
  break;

  case PARAM_PHASE_INC_3 : 
    osc_set_phase(3, val);
  break;

  case PARAM_SHAPE_0 : 
    osc_set_shape(0, val);
  break;

  case PARAM_SHAPE_1 : 
    osc_set_shape(1, val);
  break;

  case PARAM_SHAPE_2 : 
    osc_set_shape(2, val);
  break;

  case PARAM_SHAPE_3 : 
    osc_set_shape(3, val);
  break;

  case PARAM_OSC_AMP_0 : 
    mix_set_osc_amp(0, val);
  break;

  case PARAM_OSC_AMP_1 : 
    mix_set_osc_amp(1, val);
  break;

  case PARAM_OSC_AMP_2 : 
    mix_set_osc_amp(2, val);
  break;

  case PARAM_OSC_AMP_3 : 
    mix_set_osc_amp(3, val);
  break;

  case PARAM_FREQ_COARSE_0 : 
    osc_set_phi_upper(0, val);
  break;

  case PARAM_FREQ_COARSE_1 : 
    osc_set_phi_upper(1, val);
  break;

  case PARAM_FREQ_COARSE_2 : 
    osc_set_phi_upper(2, val);
  break;

  case PARAM_FREQ_COARSE_3 : 
    osc_set_phi_upper(3, val);
  break;

  } 
}